version: '3'

services:
  brryle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brryle
    environment:
      PAGE_SIZE: 5
      PUBLISH_PORT: 80
      BACKEND_URL: http://elastic:9200
    ports:
      - 80:80
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    container_name: elastic
    environment:
      - cluster.name=brryle
      - discovery.seed_hosts=elastic
      - cluster.initial_master_nodes=elastic
      - node.name=elastic
      - node.roles=master,data,ingest
      - xpack.ml.enabled=false
      - bootstrap.memory_lock=true
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
    volumes:
      - elastic_brylle:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    environment:
      - SERVER_NAME=kibana.brryle
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    ports:
      - 5601:5601
volumes:
  elastic_brylle:
    driver: local
