apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.configMap.name }}
  labels:
    app: {{ .Values.app.name }}
data:
  PAGE_SIZE: "{{ .Values.app.page.size }}"
  PUBLISH_PORT: "{{ .Values.app.service.port }}"
  BACKEND_URL: "{{ tpl .Values.app.backend.url . }}"
